# Generated by Django 2.0.2 on 2018-02-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsId', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
            ],
        ),
    ]
